# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listBuild = QtWidgets.QListWidget(self.centralwidget)
        self.listBuild.setObjectName("listBuild")
        self.horizontalLayout_4.addWidget(self.listBuild)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonNew = QtWidgets.QPushButton(self.centralwidget)
        self.buttonNew.setObjectName("buttonNew")
        self.verticalLayout.addWidget(self.buttonNew)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonRun = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRun.setObjectName("buttonRun")
        self.verticalLayout.addWidget(self.buttonRun)
        self.buttonBuild = QtWidgets.QPushButton(self.centralwidget)
        self.buttonBuild.setObjectName("buttonBuild")
        self.verticalLayout.addWidget(self.buttonBuild)
        self.buttonEdit = QtWidgets.QPushButton(self.centralwidget)
        self.buttonEdit.setObjectName("buttonEdit")
        self.verticalLayout.addWidget(self.buttonEdit)
        self.buttonFolder = QtWidgets.QPushButton(self.centralwidget)
        self.buttonFolder.setObjectName("buttonFolder")
        self.verticalLayout.addWidget(self.buttonFolder)
        self.buttonExport = QtWidgets.QPushButton(self.centralwidget)
        self.buttonExport.setObjectName("buttonExport")
        self.verticalLayout.addWidget(self.buttonExport)
        self.buttonDelete = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDelete.setObjectName("buttonDelete")
        self.verticalLayout.addWidget(self.buttonDelete)
        self.buttonCopy = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCopy.setObjectName("buttonCopy")
        self.verticalLayout.addWidget(self.buttonCopy)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonNew.setText(_translate("MainWindow", "New Build"))
        self.buttonRun.setText(_translate("MainWindow", "Run"))
        self.buttonBuild.setText(_translate("MainWindow", "Build"))
        self.buttonEdit.setText(_translate("MainWindow", "Edit"))
        self.buttonFolder.setText(_translate("MainWindow", "Build Folder"))
        self.buttonExport.setText(_translate("MainWindow", "Export"))
        self.buttonDelete.setText(_translate("MainWindow", "Delete"))
        self.buttonCopy.setText(_translate("MainWindow", "Copy"))
